name: deployment

on:
  push:
    branches:
      - development
      - beta
      - master

env:
  CI: true
  NG_CLI_ANALYTICS: false
  NODE_VERSION: 14.x
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
