name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["deployment"]
    branches: [beta]
    types:
      - completed


env:
  CI: true
  NG_CLI_ANALYTICS: false
  NODE_VERSION: 14.x
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Print Commit Message
        run: echo ${{ github.sha }} |
             echo ${{ github.event.head_commit }}
