name: deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["deployment"]
    branches: [beta]
    types:
      - completed


env:
  CI: true
  NG_CLI_ANALYTICS: false
  NODE_VERSION: 14.x
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  print-commit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Print Commit Message
        run: echo ${{ github.sha }} 
    
      - name: "Get information about the origin 'CI' run"
        uses: potiuk/get-workflow-origin@v1_1
        id: source-run-info
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}

      - name: "Print head SHA"
        run: echo ${{ steps.source-run-info.outputs.sourceHeadSha }}

  get-info:
    runs-on: ubuntu-latest
    needs: print-commit
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - name: "Print head SHA from different job"
      run: echo ${{ steps.source-run-info.outputs.sourceHeadSha }}

